import {
  addDays,
  addMonths,
  daysInRange,
  todayIso,
  type BillRow,
  type BillsReport,
  type PiggyBankRow,
  type PiggyBanksReport,
  type ProjectionEvent,
  type ProjectionReport,
  type RecurrenceRow,
  type RecurrencesReport,
} from '@shared';
import { round, type ReportContext, type Split } from '../core/ledger';
import type { FfBill, FfPiggyBank, FfPiggyBankEvent, FfRecurrence, FfResource } from '../firefly/firefly.types';

/** Months covered by one repetition of a bill frequency. */
const FREQ_MONTHS: Record<string, number> = {
  weekly: 12 / 52,
  monthly: 1,
  quarterly: 3,
  'half-year': 6,
  yearly: 12,
};

export function buildBills(ctx: ReportContext, bills: FfResource<FfBill>[], splits: Split[]): BillsReport {
  const today = todayIso();
  const p = ctx.period;
  const rows: BillRow[] = bills.map((b) => {
    const a = b.attributes;
    const cur = a.currency_code || ctx.primary;
    const conv = (v: number) => round(ctx.convert(v, cur, today));
    const min = conv(Number(a.amount_min));
    const max = conv(Number(a.amount_max));
    const avg = a.amount_avg ? conv(Number(a.amount_avg)) : round((min + max) / 2);
    const every = (FREQ_MONTHS[a.repeat_freq] ?? 1) * ((a.skip ?? 0) + 1);
    const expected = (a.pay_dates ?? []).map((d) => d.slice(0, 10)).filter((d) => d >= p.start && d <= p.end);
    const paidSplits = splits.filter((s) => s.billId === b.id);
    const paid = paidSplits.map((s) => ({ date: s.date, amount: round(ctx.value(s)), journalId: s.id }));
    const last = paidSplits.at(-1);
    const lastOriginal = last ? (last.currency === cur ? last.amount : ctx.fx.convert(last.amount, last.currency, cur, last.date).value) : null;
    const next =
      a.next_expected_match?.slice(0, 10) ?? (a.pay_dates ?? []).map((d) => d.slice(0, 10)).find((d) => d >= today) ?? null;
    return {
      id: b.id,
      name: a.name,
      active: a.active,
      currency: cur,
      amountMin: min,
      amountMax: max,
      amountAvg: avg,
      repeatFreq: a.repeat_freq,
      skip: a.skip ?? 0,
      monthlyEquivalent: a.active ? round(avg / every) : 0,
      yearlyEquivalent: a.active ? round((avg / every) * 12) : 0,
      nextDate: next,
      expectedInPeriod: expected,
      paidInPeriod: paid,
      status: paid.length ? 'paid' : expected.length ? 'pending' : 'not-expected',
      outOfRange:
        lastOriginal !== null &&
        (lastOriginal < Number(a.amount_min) - 0.005 || lastOriginal > Number(a.amount_max) + 0.005),
    };
  });
  rows.sort((x, y) => Number(y.active) - Number(x.active) || (x.nextDate ?? '9999').localeCompare(y.nextDate ?? '9999'));
  const pending = rows.filter((r) => r.active && r.status === 'pending');
  return {
    bills: rows,
    monthlyTotal: round(rows.reduce((s, r) => s + r.monthlyEquivalent, 0)),
    yearlyTotal: round(rows.reduce((s, r) => s + r.yearlyEquivalent, 0)),
    paidCount: rows.filter((r) => r.status === 'paid').length,
    pendingCount: pending.length,
    pendingAmount: round(pending.reduce((s, r) => s + r.amountAvg * r.expectedInPeriod.length, 0)),
  };
}

export function describeRepetition(rep: FfRecurrence['repetitions'][number]): string {
  return rep.description || `${rep.type}${rep.moment ? `:${rep.moment}` : ''}`;
}

export function buildRecurrences(ctx: ReportContext, recurrences: FfResource<FfRecurrence>[]): RecurrencesReport {
  const today = todayIso();
  const rows: RecurrenceRow[] = recurrences.map((r) => {
    const a = r.attributes;
    const t = a.transactions[0];
    const cur = t?.currency_code || ctx.primary;
    const occurrences = [...new Set(a.repetitions.flatMap((rep) => (rep.occurrences ?? []).map((d) => d.slice(0, 10))))]
      .filter((d) => d >= today)
      .sort()
      .slice(0, 6);
    return {
      id: r.id,
      title: a.title,
      type: a.type,
      active: a.active,
      amount: round(a.transactions.reduce((s, tx) => s + ctx.convert(Number(tx.amount), tx.currency_code || ctx.primary, today), 0)),
      currency: cur,
      repetition: a.repetitions.map(describeRepetition).join(' · '),
      source: t?.source_name ?? '',
      destination: t?.destination_name ?? '',
      category: t?.category_name ?? null,
      nextOccurrences: occurrences,
      repeatUntil: a.repeat_until?.slice(0, 10) ?? null,
    };
  });
  rows.sort((x, y) => Number(y.active) - Number(x.active) || (x.nextOccurrences[0] ?? '9999').localeCompare(y.nextOccurrences[0] ?? '9999'));
  return { recurrences: rows };
}

/**
 * Cash-flow projection: current liquid balance + expected recurring transactions and bills.
 * Bills already generated by a recurrence are not counted twice; transfers are ignored
 * because they do not change the combined asset balance.
 */
export function buildProjection(
  ctx: ReportContext,
  startBalance: number,
  days: number,
  bills: FfResource<FfBill>[],
  recurrences: FfResource<FfRecurrence>[],
): ProjectionReport {
  const today = todayIso();
  const end = addDays(today, days);
  const events: ProjectionEvent[] = [];
  const billsViaRecurrence = new Set<string>();

  for (const r of recurrences) {
    const a = r.attributes;
    if (!a.active || a.type === 'transfer') continue;
    for (const t of a.transactions) {
      const billId = t.subscription_id ?? t.bill_id;
      if (billId) billsViaRecurrence.add(String(billId));
    }
    const sign = a.type === 'deposit' ? 1 : -1;
    for (const rep of a.repetitions) {
      for (const raw of rep.occurrences ?? []) {
        const date = raw.slice(0, 10);
        if (date <= today || date > end) continue;
        const amount = a.transactions.reduce((s, t) => s + ctx.convert(Number(t.amount), t.currency_code || ctx.primary, date), 0);
        events.push({ date, name: a.title, kind: 'recurrence', amount: round(sign * amount) });
      }
    }
  }
  for (const b of bills) {
    const a = b.attributes;
    if (!a.active || billsViaRecurrence.has(b.id)) continue;
    const avg = (Number(a.amount_min) + Number(a.amount_max)) / 2;
    for (const raw of a.pay_dates ?? []) {
      const date = raw.slice(0, 10);
      if (date <= today || date > end) continue;
      events.push({ date, name: a.name, kind: 'bill', amount: round(-ctx.convert(avg, a.currency_code || ctx.primary, date)) });
    }
  }
  events.sort((x, y) => x.date.localeCompare(y.date));

  let balance = startBalance;
  let lowest = { date: today, balance: startBalance };
  const series = daysInRange(today, end).map((date) => {
    const todays = events.filter((e) => e.date === date);
    const inflow = todays.filter((e) => e.amount > 0).reduce((s, e) => s + e.amount, 0);
    const outflow = todays.filter((e) => e.amount < 0).reduce((s, e) => s - e.amount, 0);
    balance += inflow - outflow;
    if (balance < lowest.balance) lowest = { date, balance: round(balance) };
    return { date, balance: round(balance), inflow: round(inflow), outflow: round(outflow) };
  });
  const horizons = [30, 60, 90]
    .filter((h) => h <= days)
    .map((h) => ({ days: h, balance: series[Math.min(h, series.length - 1)].balance }));

  return { startBalance: round(startBalance), days: series, events, horizons, lowest };
}

export function buildPiggyBanks(
  ctx: ReportContext,
  piggies: FfResource<FfPiggyBank>[],
  events: Map<string, FfPiggyBankEvent[]>,
): PiggyBanksReport {
  const today = todayIso();
  const since = addMonths(today, -6);
  const rows: PiggyBankRow[] = piggies
    .filter((p) => p.attributes.active !== false)
    .map((p) => {
      const a = p.attributes;
      const cur = a.currency_code || ctx.primary;
      const conv = (v: number) => round(ctx.convert(v, cur, today));
      const target = a.target_amount && Number(a.target_amount) > 0 ? conv(Number(a.target_amount)) : null;
      const current = conv(Number(a.current_amount) || 0);
      const left = target !== null ? Math.max(target - current, 0) : null;
      const recent = (events.get(p.id) ?? []).filter((e) => e.created_at.slice(0, 10) >= since);
      const contributed = recent.reduce((s, e) => s + Number(e.amount), 0);
      const monthlyPace = Math.max(conv(contributed) / 6, 0);
      let estimatedDate: string | null = null;
      if (left !== null) {
        if (left <= 0) estimatedDate = today;
        else if (monthlyPace > 0) estimatedDate = addDays(today, Math.ceil((left / monthlyPace) * 30.44));
      }
      const targetDate = a.target_date?.slice(0, 10) ?? null;
      return {
        id: p.id,
        name: a.name,
        currency: cur,
        target,
        current,
        leftToSave: left !== null ? round(left) : null,
        pct: target ? Math.min(current / target, 1) : null,
        startDate: a.start_date?.slice(0, 10) ?? null,
        targetDate,
        monthlyPace: round(monthlyPace),
        estimatedDate,
        onTrack: targetDate && estimatedDate ? estimatedDate <= targetDate : targetDate && left ? false : null,
        accounts: (a.accounts ?? []).map((x) => x.name),
        group: a.object_group_title ?? null,
      };
    })
    .sort((x, y) => (y.pct ?? 0) - (x.pct ?? 0));
  return {
    piggyBanks: rows,
    totalSaved: round(rows.reduce((s, r) => s + r.current, 0)),
    totalTarget: round(rows.reduce((s, r) => s + (r.target ?? 0), 0)),
  };
}
